name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate local trophy SVG
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: Grahamm-drx
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: dist/trophy.svg
          theme: dracula

      - name: Push trophy.svg to trophy-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: trophy-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
